version: '3'

services:
  load_balancer:
    build:
      context: .infrastructure/load-balancer
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - uk_server
      - us_server_1
      - us_server_2
      - rest_server
      - backup_server

  uk_server:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./.infrastructure/nginx/uk.conf:/etc/nginx/conf.d/default.conf

  us_server_1:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./.infrastructure/nginx/us-1.conf:/etc/nginx/conf.d/default.conf

  us_server_2:
    image: nginx:latest
    ports:
      - "8002:80"
    volumes:
      - ./.infrastructure/nginx/us-2.conf:/etc/nginx/conf.d/default.conf

  rest_server:
    image: nginx:latest
    ports:
      - "8003:80"
    volumes:
      - ./.infrastructure/nginx/rest.conf:/etc/nginx/conf.d/default.conf

  backup_server:
    image: nginx:latest
    ports:
      - "8004:80"
    volumes:
      - ./.infrastructure/nginx/backup.conf:/etc/nginx/conf.d/default.conf
